# Generated by Django 5.2.6 on 2025-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role1', models.CharField(default='Trainee', max_length=100)),
                ('role2', models.CharField(default='Python Developer', max_length=100)),
                ('bio', models.TextField(default="I'm currently on a journey to become a Python developer.")),
                ('profile_image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
